package gog.my_project.data_base.query.dialect.nodes.select_nodes.condition_item_collection

import gog.my_project.data_base.query.ast.interfaces.select_interface.condition_item_collection.IQueryConditionsCollectionAst
import gog.my_project.data_base.query.dialect.data_class.select_data.conditions_item_collection.QueryConditionCollectionData
import gog.my_project.data_base.query.renderer.interfaces.IAstRenderer

interface IQueryConditionCollectionCapability: IAstRenderer<IQueryConditionsCollectionAst, QueryConditionCollectionData> {
}